# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dafa0a1726162c2ac5e32b109dafc69f803a8b24514ef86b8de404f991d8732d6faf73a17f6787773113be4b338a5da9064ca83ebcd11e90d61b06012429882f

test:
  secret_key_base: dafa0a1726162c2ac5e32b109dafc69f803a8b24514ef86b8de404f991d8732d6faf73a17f6787773113be4b338a5da9064ca83ebcd11e90d61b06012429882f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: Setting.secret_key_base

staging:
  secret_key_base: Setting.secret_key_base
